# -*- coding: utf-8 -*-
"""Parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y0rkwdX-pj9oC_g_lFrB4XeiDAPBmiS8
"""

import requests
import json
import re
import os

def get_reviews_on_page(endCursor, movieId):
    r = requests.get(f"https://www.rottentomatoes.com/napi/movie/{movieId}/reviews/user",
    params = {
        "direction": "next",
        "endCursor": endCursor,
        "startCursor": ""
    })
    return r.json()

def get_reviews(url: str):
    reviews = []
    url=url
    filmname = url.split('/')[4]
    print(filmname)
    result = requests.get(url)
    data = json.loads(re.search('movieReview\s=\s(.*);', result.text).group(1))
    movieId = data["movieId"]
    # os.mkdir(f'Data/{filmname}')
    for i in range(0, 10):
        try:
            result = get_reviews_on_page(result["pageInfo"]["endCursor"] if i != 0  else "", movieId)
            count = 0
            for t in result["reviews"]:
                count += 1
                reviews.append(t["review"])
                # with open(f'Data/{filmname}/{filmname}_{i+1}_{count}.txt', 'w') as f:
                    # f.write(t['review'])
            print(f"reviews from page [{i+1}] have been added")
        except:
            print('No more pages with reviews')
            break
    return reviews

